name: "Build and Release xml2txt"

on:
  push:

concurrency:
  group: "build"
  cancel-in-progress: true
  
jobs:
  build-linux64:
    name: "Linux 64-bit"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: sudo apt-get install -y --no-install-recommends fpc
    - run: mkdir -p bin obj && make && cp bin/xml2txt xml2txt-linux64
    - uses: actions/upload-artifact@v4
      with:
        name: xml2txt-linux64
        path: xml2txt-linux64

  release:
    name: "Release All"
    runs-on: ubuntu-latest
    needs:
      - build-linux64

    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4

    - uses: actions/download-artifact@v4
      with:
        name: xml2txt-linux64
        path: .

    - name: Delete old release
      run: gh release delete "latest" --cleanup-tag -y || true
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Create new release
      run: gh release create -t "latest" "latest" xml2txt* -n "Latest release"
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
